# Generated by Django 5.0 on 2024-05-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='certificate',
            field=models.TextField(default='no info', verbose_name='Лицензия'),
            preserve_default=False,
        ),
    ]
